module.exports = [
  {
    id: 1,
    user_id: 1,
    bean_id: 1,
    method_id: 1,
    dose: "18g",
    output: "36g",
    time: "28s",
    water: "",
    temp: "96C",
    grind: "10",
    ratio: "",
    notes: ""
  },
  {
    id: 2,
    user_id: 1,
    bean_id: 2,
    method_id: 1,
    dose: "19g",
    output: "38g",
    time: "29s",
    water: "",
    temp: "94C",
    grind: "12",
    ratio: "",
    notes: ""
  },
  {
    id: 3,
    user_id: 1,
    bean_id: 2,
    method_id: 2,
    dose: "28g",
    output: "",
    time: "4m",
    water: "450g",
    temp: "96C",
    grind: "15",
    ratio: "",
    notes: ""
  },
  {
    id: 4,
    user_id: 1,
    bean_id: 3,
    method_id: 3,
    dose: "16g",
    output: "",
    time: "28s",
    water: "248g",
    temp: "98C",
    grind: "13",
    ratio: "",
    notes: ""
  },
  {
    id: 5,
    user_id: 1,
    bean_id: 4,
    method_id: 1,
    dose: "18g",
    output: "38g",
    time: "30s",
    water: "",
    temp: "95C",
    grind: "9",
    ratio: "",
    notes: "" }
]